name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          # Пример: установка Python-зависимостей
          pip install -r requirements.txt

      - name: Build application
        run: |
          echo "Building application..."
          # Здесь добавьте реальные команды для сборки

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests..."
          # Реальные команды тестирования (например, pytest)

      - name: Run tests
        run: pytest

